create table category (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    description varchar(2000),
    icon varchar(32)
);

create index idx_category_name on category (name);

create table category_parent_child (
    parent_id bigint not null references category(id) on delete cascade,
    child_id bigint not null references category(id) on delete cascade,
    constraint uq_category_parent_child unique (parent_id, child_id),
    constraint uq_category_single_parent unique (child_id)
);

create index idx_category_parent_child_parent on category_parent_child (parent_id);

create table category_parent_child_all (
    ancestor_id bigint not null references category(id) on delete cascade,
    descendant_id bigint not null references category(id) on delete cascade,
    constraint uq_category_parent_child_all unique (ancestor_id, descendant_id)
);

create index idx_category_parent_child_all_descendant on category_parent_child_all (descendant_id);

create table movie_category (
    movie_id varchar(32) not null references movies(imdb_id) on delete cascade,
    category_id bigint not null references category(id) on delete cascade,
    constraint pk_movie_category primary key (movie_id, category_id)
);

create index idx_movie_category_category on movie_category (category_id, movie_id);
