-- category_parent_child becomes a general-purpose many-to-many DAG edge table: a category may now have more
-- than one parent (e.g. a Movie Guide linking in a category that also lives natively elsewhere in the tree).
alter table category_parent_child drop constraint uq_category_single_parent;

create table movie_guide (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    description varchar(2000),
    icon varchar(32),
    owner varchar(255) not null,
    category_id bigint not null references category(id) on delete cascade
);

create index idx_movie_guide_category on movie_guide (category_id);
create index idx_movie_guide_owner on movie_guide (owner);

-- One row per category that is a "default member" of a guide. referenced_category_id is null when the category
-- was created natively inside the guide's own sandbox, and set (to the same id as category_id -- no row
-- duplication) when it is a Copy-linked reference whose real home is elsewhere in the tree.
create table movie_guide_default_category (
    movie_guide_id bigint not null references movie_guide(id) on delete cascade,
    category_id bigint not null references category(id) on delete cascade,
    referenced_category_id bigint references category(id) on delete cascade,
    constraint uq_movie_guide_default_category unique (movie_guide_id, category_id)
);

create index idx_movie_guide_default_category_category on movie_guide_default_category (category_id);
create index idx_movie_guide_default_category_referenced on movie_guide_default_category (referenced_category_id);
