-- Private-category table group backing "My Watchlists": same shape as category/category_parent_child/
-- category_parent_child_all (V34, V38), but a fully separate table group so private data is never joined into
-- the public category tree.
create table private_category (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    description varchar(2000),
    icon varchar(32)
);

create index idx_private_category_name on private_category (name);

create table private_category_parent_child (
    parent_id bigint not null references private_category(id) on delete cascade,
    child_id bigint not null references private_category(id) on delete cascade,
    constraint uq_private_category_parent_child unique (parent_id, child_id)
);

create index idx_private_category_parent_child_parent on private_category_parent_child (parent_id);

create table private_category_parent_child_all (
    ancestor_id bigint not null references private_category(id) on delete cascade,
    descendant_id bigint not null references private_category(id) on delete cascade,
    constraint uq_private_category_parent_child_all unique (ancestor_id, descendant_id)
);

create index idx_private_category_parent_child_all_descendant on private_category_parent_child_all (descendant_id);

-- Same finder/creator as get_or_create_category() (V35), retargeted at the private tables.
create or replace function get_or_create_private_category(p_parent_id bigint, p_name varchar, p_icon varchar default null)
    returns bigint
    language plpgsql
as $$
declare
    v_id bigint;
begin
    perform pg_advisory_xact_lock(hashtext('private:' || coalesce(p_parent_id::text, 'root') || ':' || lower(p_name)));

    select c.id into v_id
    from private_category c
    join private_category_parent_child pc on pc.child_id = c.id
    where pc.parent_id = coalesce(p_parent_id, c.id)
      and lower(c.name) = lower(p_name)
    limit 1;

    if v_id is not null then
        return v_id;
    end if;

    insert into private_category (name, icon) values (p_name, p_icon) returning id into v_id;

    insert into private_category_parent_child_all (ancestor_id, descendant_id) values (v_id, v_id);
    insert into private_category_parent_child (parent_id, child_id) values (coalesce(p_parent_id, v_id), v_id);

    if p_parent_id is not null then
        insert into private_category_parent_child_all (ancestor_id, descendant_id)
        select ancestor_id, v_id from private_category_parent_child_all where descendant_id = p_parent_id;
    end if;

    return v_id;
end;
$$;
