-- "My Watchlists": user_movie_watchlist mirrors movie_guide (V38) minus `type`, anchored in private_category
-- instead of the public category tree. movie_watchlist_movie is the flat "movie is directly in this watchlist"
-- membership table (populated when a movie is added with no specific private sub-category chosen).
-- movie_private_category mirrors movie_category for movies filed into a watchlist's private sub-categories.
-- movie_watchlist_default_category is the "subscribed" pointer table: unlike movie_guide_default_category it
-- never copy-links into the private tree -- the row itself *is* the subscription.
create table user_movie_watchlist (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    description varchar(2000),
    icon varchar(32),
    owner varchar(255) not null,
    category_id bigint not null references private_category(id) on delete cascade
);

create index idx_user_movie_watchlist_category on user_movie_watchlist (category_id);
create index idx_user_movie_watchlist_owner on user_movie_watchlist (owner);
create unique index uq_user_movie_watchlist_owner_name on user_movie_watchlist (owner, lower(name));

create table movie_watchlist_movie (
    movie_watchlist_id bigint not null references user_movie_watchlist(id) on delete cascade,
    movie_id varchar(32) not null references movies(imdb_id) on delete cascade,
    constraint pk_movie_watchlist_movie primary key (movie_watchlist_id, movie_id)
);

create index idx_movie_watchlist_movie_movie on movie_watchlist_movie (movie_id);

create table movie_private_category (
    movie_id varchar(32) not null references movies(imdb_id) on delete cascade,
    private_category_id bigint not null references private_category(id) on delete cascade,
    constraint pk_movie_private_category primary key (movie_id, private_category_id)
);

create index idx_movie_private_category_category on movie_private_category (private_category_id, movie_id);

create table movie_watchlist_default_category (
    watchlist_id bigint not null references user_movie_watchlist(id) on delete cascade,
    category_id bigint not null references category(id) on delete cascade,
    constraint uq_movie_watchlist_default_category unique (watchlist_id, category_id)
);

create index idx_movie_watchlist_default_category_category on movie_watchlist_default_category (category_id);
