-- Mirrors V54 for the private/watchlist side, with one extra wrinkle: a private (watchlist-owned) composition
-- can combine both private categories AND existing public categories as components (this is what lets a
-- watchlist "follow" a public category like "New 2026", same as today's Subscribe feature does) -- so a
-- component row references EITHER a private_category OR a public category, never both.
alter table private_composition_category add column operator smallint not null default 1 check (operator in (0, 1));

drop trigger private_composition_component_must_be_normal on private_composition_category_component;

-- Widen the component reference to be polymorphic: exactly one of component_category_id (private) /
-- public_component_category_id (public) is set per row. The old compound primary key can't survive
-- component_category_id becoming nullable (primary key columns are implicitly NOT NULL), so it's replaced by a
-- surrogate id plus two partial unique indexes (one per component kind) that still prevent duplicates.
alter table private_composition_category_component drop constraint pk_private_composition_category_component;
alter table private_composition_category_component alter column component_category_id drop not null;
alter table private_composition_category_component add column public_component_category_id bigint references category(id) on delete cascade;
alter table private_composition_category_component add column id bigint generated by default as identity primary key;

alter table private_composition_category_component
    drop constraint chk_private_composition_category_component_not_self,
    add constraint chk_private_composition_category_component_not_self
        check (component_category_id is null or composition_category_id <> component_category_id),
    add constraint chk_private_composition_category_component_one_component
        check ((component_category_id is not null) <> (public_component_category_id is not null));

create unique index uq_private_composition_category_component_private
    on private_composition_category_component(composition_category_id, component_category_id)
    where component_category_id is not null;

create unique index uq_private_composition_category_component_public
    on private_composition_category_component(composition_category_id, public_component_category_id)
    where public_component_category_id is not null;

do $$
declare
    fkey_name text;
begin
    select conname into fkey_name
    from pg_constraint
    where conrelid = 'private_composition_category_component'::regclass
      and contype = 'f'
      and confrelid = 'private_category'::regclass
      and conkey = (select array_agg(attnum) from pg_attribute
                    where attrelid = 'private_composition_category_component'::regclass and attname = 'component_category_id');

    execute format('alter table private_composition_category_component drop constraint %I', fkey_name);
    execute format('alter table private_composition_category_component add constraint %I foreign key (component_category_id) references private_category(id) on delete cascade', fkey_name);
end $$;

create function cascade_delete_empty_private_compositions() returns trigger language plpgsql as $$
declare
    empty_id bigint;
begin
    for empty_id in
        select distinct d.composition_category_id
        from deleted_components d
        where d.component_category_id is not null
          and not exists (
            select 1 from private_composition_category_component remaining
            where remaining.composition_category_id = d.composition_category_id
        )
    loop
        delete from private_category where id = empty_id;
    end loop;
    return null;
end;
$$;

create trigger cascade_delete_empty_private_compositions_trigger
after delete on private_composition_category_component
referencing old table as deleted_components
for each statement
execute function cascade_delete_empty_private_compositions();

-- private_category_movie_match's fixed-point iteration mirrors compute_category_movie_match, plus a second
-- "satisfied" source: a public component's match status is simply read from the (already fully resolved, however
-- deeply nested) public category_movie_match view -- a private composition can depend on a public category, but
-- never the reverse, so there's no risk of the two fixed-point computations needing each other circularly.
drop view private_category_movie_match;

create function compute_private_category_movie_match() returns table(private_category_id bigint, movie_id varchar) language plpgsql as $$
declare
    inserted_count int;
    iteration int := 0;
begin
    drop table if exists pg_temp.private_category_movie_match_resolved;
    create temporary table private_category_movie_match_resolved (private_category_id bigint, movie_id varchar(32));

    insert into private_category_movie_match_resolved (private_category_id, movie_id)
    select cpc.ancestor_id, mc.movie_id
    from private_category_parent_child_all cpc
    join movie_private_category mc on mc.private_category_id = cpc.descendant_id
    where not exists (select 1 from private_composition_category cc where cc.private_category_id = cpc.ancestor_id);

    loop
        iteration := iteration + 1;
        exit when iteration > 50;

        insert into private_category_movie_match_resolved (private_category_id, movie_id)
        select matched.private_category_id, matched.movie_id
        from (
            with satisfied as (
                select comp.composition_category_id, comp.component_category_id as private_component,
                       comp.public_component_category_id as public_component, r.movie_id
                from private_composition_category_component comp
                join private_category_movie_match_resolved r on r.private_category_id = comp.component_category_id
                where comp.component_category_id is not null

                union all

                select comp.composition_category_id, comp.component_category_id, comp.public_component_category_id, p.movie_id
                from private_composition_category_component comp
                join category_movie_match p on p.category_id = comp.public_component_category_id
                where comp.public_component_category_id is not null
            )
            select cc.private_category_id, s.movie_id
            from private_composition_category cc
            join satisfied s on s.composition_category_id = cc.private_category_id
            where cc.operator = 1 -- Operator.AND
            group by cc.private_category_id, s.movie_id
            having count(distinct coalesce(s.private_component, -s.public_component)) = (
                select count(*) from private_composition_category_component req
                where req.composition_category_id = cc.private_category_id
            )

            union

            select cc.private_category_id, s.movie_id
            from private_composition_category cc
            join satisfied s on s.composition_category_id = cc.private_category_id
            where cc.operator = 0 -- Operator.OR
        ) matched
        where not exists (
            select 1 from private_category_movie_match_resolved existing
            where existing.private_category_id = matched.private_category_id and existing.movie_id = matched.movie_id
        );

        get diagnostics inserted_count = row_count;
        exit when inserted_count = 0;
    end loop;

    return query select r.private_category_id, r.movie_id from private_category_movie_match_resolved r;

    drop table private_category_movie_match_resolved;
    return;
end;
$$;

create view private_category_movie_match as select * from compute_private_category_movie_match();
