server:
  port: 8079

spring:
  application:
    name: movie-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/movies}

  cloud:
    compatibility-verifier:
      enabled: false
    discovery:
      enabled: false
      blocking:
        enabled: false
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: movies-api-websocket
              uri: ${MOVIES_API_URL:http://movies-api:8080}
              order: -1
              predicates:
                - Path=/api/movies/ws,/api/movies/ws/**
              filters:
                - RewritePath=/api/movies/ws(?<segment>/?.*), /ws$\{segment}

            - id: movies-api
              uri: ${MOVIES_API_URL:http://movies-api:8080}
              order: 0
              predicates:
                - Path=/api/movies

            - id: movies-api-relative-paths
              uri: ${MOVIES_API_URL:http://movies-api:8080}
              order: 1
              predicates:
                - Path=/api/movies/**
              filters:
                - RewritePath=/api/movies/(?<segment>.*), /api/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  expected-audience: ${EXPECTED_USER_AUDIENCE:movies-ui}

keycloak:
  token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/movies/protocol/openid-connect/token}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls-primary-name: movies
    persist-authorization: true
    oauth:
      client-id: movies-ui
    urls:
      - name: movies
        url: /v3/api-docs/movies
